zloirock/core-js

- bower.json
This fixes some issues with the bower.json:
* authors has wrong format
* homepage has wrong format (missing scheme)
* added repository info
More info: https://github.com/bower/bower.json-spec
The malformed homepage url currently breaks packaging with https://rails-assets.org.
> Fix bower.json Format

- LICENSE
Your `package.json` says the license is MIT, but I generally find it's much easier quickly glance at a file in the root.
> MIT license?

- build/build.ls
- tests/tests/es6.array.copy-within.ls
- tests/tests/es6.array.fill.ls
- tests/tests/es6.object.to-string.ls
- tests/tests/es6.string.code-point-at.ls
- tests/tests/es6.string.ends-with.ls
- tests/tests/es6.string.includes.ls
- tests/tests/es6.string.repeat.ls
- tests/tests/es6.string.starts-with.ls
- tests/tests/es7.array.includes.ls
- tests/tests/es7.string.at.ls
PhantonJS 1.x (and old versions of webkit, Safari, etc) don't properly
handle "use strict" directives if they are nested in functions more than
two deep.  Add a top-level "use strict" inside the first nested function
scope in order to prevent this bug from affecting core-js.
> Fix strict mode when testing with PhantomJS 1.x.

- modules/es5.js
The Date#toISOString function in PhantonJS 1.x (and old versions of
webkit, Safari, etc) returns "-01" in the millisecond field in some
cases.  Test for this and ensure that we override the native
implementation in this case.
> Ensure that we replace Date#toISOString if native implementation is broken

- modules/es6.regexp.js
This is a fix for PhantomJS (and older versions of webkit/Safari).
> Ensure that "new RegExp" always creates a new object.

- tests/tests/es6.reflect.ls
In PhantomJS (and older webkit and Safari) we stub out Object.freeze
using an identity function.  Test to see whether we have a functional
Object.freeze before using it in our test suite.
> Check whether Object.freeze is stubbed out before using it in tests.

- package.json
This makes it much less likely you'll be surprised by testing out-of-date
sources.
I could have added a bunch of different targets ("npm run build", "npm run rebuild", "npm run quick-test", etc) but I think it's best if `npm test` just does the thing which is most correct, even if it's not the fastest way to (re)run the test suite.
> Ensure that 'npm test' rebuilds before testing.

- tests/tests-library/es6.promise.ls
- tests/tests/es6.promise.ls
Add a subclass test for the Promise implementation.
This passes on iojs, Chrome, and Firefox, using native Promises, and passes in PhantomJS and Opera using core-js's Promise implementation.  It fails in Firefox 33.0.0 using its native Promises; see https://github.com/babel/babel/issues/1320#issuecomment-95654726
> Add subclass tests for Promise

- modules/es6.math.js
- tests/tests/es6.math.ls
Math.hypot will now correctly use the largest (absolute) value for normalization. 
This also fixes a bug where hypot would return a negative result if the first argument is negative.
> Fix Math.hypot normalization issues

- modules/es7.regexp.escape.js
Hey, updating the polyfill based on change in https://github.com/benjamingr/RexExp.escape, based on usage data escaping it isn't required (see the data folder for more motivation for this decision).
> Do not escape `/`

- modules/es6.array.from.js
Certain minifiers will reuse references, which breaks in Safari8 and IE<10
Addresses Issue  #111
> Make Array.from more Minifier friendly.

- library/modules/$.task.js
- modules/$.task.js
This typo is causing Firefox to improperly schedule tasks in WebWorker environments as setImmediate is not available there.
> Fix typo for importScript -> importScripts

- build/build.ls
- build/index.js
Adds an `exportCore` option to core-js-builder that defaults to true.
If set to false, the compiled output will not contain a UMD wrapper to export the core library.
In one of our projects, we're using core-js to polyfill native Promises, but the UMD wrapper here causes problems with our test runner (because we're using r.js in our test runner, and it doesn't support the anonymous define module format).
Because we're only relying on core-js to polyfill functionality into the global scope, the exported package is unneeded- so this option would allow us to not export anything.
> Allow user to specify that built output should not export core

- library/modules/_object-gopn-ext.js
- modules/_object-gopn-ext.js
There's an issue that would cause `Object.getOwnPropertyNames(window)` to return outdated results in some browsers. It would try to call the native `Object.getOwnPropertyNames` and then fall back, but there was a mistake in the try block so it would always fall back.
(This caused some really fun issues when mixing Babel code where some used the transform-runtime plugin and some didn't. Before I realized the cause of it was so simple, I started documenting this [example](https://github.com/AgentME/regenfail) because I imagined the fix would be much more involved.)
> Fix Object.getOwnPropertyNames(window) replacement

- modules/_object-create.js
We experienced issues with inlining this code and parsing by facebook parser. So it's indeed safer to incorporate this.
> #204 Escaping script tags

- modules/library/web.dom.iterable.js
- modules/web.dom.iterable.js
- tests/library/web.dom.iterable.ls
- tests/tests/web.dom.iterable.ls
Posting for discussion given https://github.com/babel/babel/issues/4616. Not a complete fix because I wanted to get your thoughts before going further.
As far as I can tell, and given the behavior in Chrome and FF, these are supposed to be iterable because of the behavior documented in https://heycam.github.io/webidl/#es-iterators for IDL. It says any integer-indexed class should be considered iterable automatically, but only those explicitly marked `Iterable` in the IDL should get `keys`, `values` and `entries`.
Given that, the current behavior of of MediaList, StyleSheetList, and CSSRuleList aren't quite right since they should not have an `.keys`, `.values` and `.entries`. Only NodeList and DOMTokenList are explicitly `Iterable<>` in the DOM spec.
I've pulled in a list of DOM classes …
> Incomplete iterable DOM changes for discussion

- README.md
fixed typo: "marchAll" to "matchAll"
> Small typo fix in README.md (marchAll -> matchAll)

- modules/_task.js
[miniSphere](https://github.com/fatcerberus/minisphere) is JavaScript game engine maintained by myself and using the Duktape ES5 engine.  My environment doesn't have any of the async harnesses (setTimeout, postMessage, etc.) supported by browsers, but *does* have a function, `Dispatch.now()`, that serves the same purpose.  the core-js Promise implementation doesn't currently work in my environment because of this; this pull adds support for it.
> Add support for Sphere Dispatch API

- packages/core-js-compat/README.md
Otherwise, the link is broken on `core-js-compat` npm page: https://www.npmjs.com/package/core-js-compat
> Make link to CONTRIBUTING.md absolute

- packages/core-js/features/array/flat-map.js
- packages/core-js/features/array/flat.js
- packages/core-js/features/object/index.js
- packages/core-js/stable/array/flat-map.js
- packages/core-js/stable/array/flat.js
- packages/core-js/stable/object/index.js
While looking through the code, I found some duplicated `module.exports` assignments, which were probably copy-paste errors. This PR replaces them all :spaghetti:
> Fix duplicated assignment to module.exports

- packages/core-js/modules/es.object.get-own-property-names.js
rollup treeshaking is removing the Object.getOwnPropertyNames
FAILS_ON_PRIMITIVES feature test.
This is related to these rollup issue
https://github.com/rollup/rollup/issues/1771
https://github.com/rollup/rollup/issues/2790
Related core-js issues
#494 
#513
> Adds workaround for rollup treeshaking issue

- packages/core-js/internals/object-get-own-property-symbols-external.js
- packages/core-js/modules/es.symbol.js
- tests/compat/tests.js
- tests/pure/es.symbol.js
- tests/tests/es.symbol.js
This is a workaround for this chrome issue
https://bugs.chromium.org/p/v8/issues/detail?id=3443
Without this fix, the object spread operator is broken for these
versions of chrome when transpiling and shimming with babel and
core-js@3.
See https://github.com/babel/babel/issues/8721
> Fix broken getOwnPropertySymbols in Mobile Chrome 38 and 39

- packages/core-js/internals/task.js
This addresses a security concern where messages can be intercepted and/or sent to
any window that uses '*' as the 2nd parameter (the origin) to postMessage.
Per the [OWASP HTML5 Security Cheat Sheet](https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/HTML5_Security_Cheat_Sheet.md):
> When posting a message, explicitly state the expected origin as the second argument to postMessage rather than * in order to prevent sending the message to an unknown origin after a redirect or some other means of the target window's origin changing.
MDN's docs also state: 
> Always provide a specific targetOrigin, not *, if you know where the other window's document should be located. Failing to provide a specific target discloses the data you send to any interested malicious site
I see 2 …
> Use global.location.host over '*' in global.postMessage

- packages/core-js/modules/es.regexp.to-string.js
- tests/tests/es.regexp.to-string.js
When the flags property is not available on `RegExp`, the internals `regexp-flags` implementation should be used regardless of `DESCRIPTORS`.
Fixes: zloirock/core-js#536
I'm not *certain* this is the right fix, but the value of `DESCRIPTORS` is `true` on IE 11 and the internals implementation would be fine - and doesn't seem to depend on `defineProperty`.
Also not sure how to include a focused test, but the linked issue has a project that reproduces the problem.
> Give correct RegExp flags in toString

- CONTRIBUTING.md
The NPM lint script referenced is actually `lint` not `eslint`
> Fix incorrect command in CONTRIBUTING.md

- packages/core-js/scripts/postinstall.js
> Update postinstall script to honor npm color config

- README.md
> README: Move description to the top of the file

- packages/core-js/scripts/postinstall.js
The main [opencollective-postinstall](https://www.npmjs.com/package/opencollective-postinstall) package uses the `DISABLE_OPENCOLLECTIVE` environment variable to determine whether or not the ad should be shown. The webpack-cli package [does this too](https://github.com/webpack/webpack-cli/blob/08edf5766afc3201689eeaf56cfaaad567a22633/bin/opencollective.js#L40).
This PR adds support for hiding the open collective ad when `DISABLE_OPENCOLLECTIVE` is set to true.
> respect DISABLE_OPENCOLLECTIVE env variable

- packages/core-js-compat/index.js
- packages/core-js-compat/package.json
- packages/core-js-compat/src/build-entries.js
Ref: https://github.com/babel/babel/pull/10158#issuecomment-508285566
> [core-js-compat] Filter available modules without using an intermediate set

- packages/core-js-compat/src/data.js
Looks like `es.string.match-all` is supported in Firefox 67. MDN also confirms this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/matchAll#Browser_compatibility
Thanks!
> update core-js-compat for Firefox 67

- packages/core-js-compat/src/build-entries.js
Check for both backwards and forwards slashes so the regex matches paths found by windows as well. Fixes #605
> Check for backwards slashes in module regex

- CHANGELOG.md
- packages/core-js-compat/src/data.js
- packages/core-js/modules/es.string.match-all.js
- packages/core-js/modules/esnext.string.replace-all.js
- packages/core-js/modules/esnext.symbol.replace-all.js
- tests/commonjs.js
- tests/compat/tests.js
- tests/pure/es.string.match-all.js
- tests/pure/esnext.string.replace-all.js
- tests/tests/es.string.match-all.js
- tests/tests/esnext.string.replace-all.js
per https://github.com/tc39/proposal-string-replaceall/pull/24 and the decision from TC39 meetings
> `String#{ matchAll, replaceAll }` throws a error on non-global regex argument

- packages/core-js/modules/web.url-search-params.js
Fix the following error occurred in WeChat Windows client (based on Chrome 53 from UA), when passing an `URLSearchParams` as body and not passing headers.
message: "Failed to construct 'Headers': No matching constructor signature."
stack: TypeError: Failed to construct 'Headers': No matching constructor signature.
at TypeError (native)
at fetch (webpack-internal:///./node_modules/core-js/modules/web.url-search-params.js:328:23)
at _callee$ (webpack-internal:///./src/api/internal.ts:180:20)
at tryCatch (webpack-internal:///./node_modules/regenerator-runtime/runtime.js:45:40)
...
> Fix an error when using URLSearchParams with fetch

- README.md
a few of the methods introduced in the Iterator Helpers proposal are incorrectly documented. they should return promises.
code: https://github.com/zloirock/core-js/blob/v3.4.7/packages/core-js/internals/async-iterator-iteration.js#L21
> updated AsyncIterator helpers documentation

- packages/core-js/internals/object-create.js
> alternative for object.create under IE8 #727

- packages/core-js-compat/src/data.js
- packages/core-js/es/index.js
- packages/core-js/es/regexp/index.js
- packages/core-js/es/regexp/sticky.js
- packages/core-js/internals/fix-regexp-well-known-symbol-logic.js
- packages/core-js/internals/regexp-exec.js
- packages/core-js/internals/regexp-sticky-helpers.js
- packages/core-js/modules/es.regexp.constructor.js
- packages/core-js/modules/es.regexp.flags.js
- packages/core-js/modules/es.regexp.sticky.js
- packages/core-js/modules/es.regexp.test.js
- packages/core-js/modules/es.string.replace.js
- tests/compat/tests.js
- tests/tests/es.regexp.exec.js
- tests/tests/es.regexp.sticky.js
- tests/tests/es.regexp.test.js
- tests/tests/index.js
This PR implements the sticky flag for Regular Expressions and `RegExp#test` delegation to `RegExp#exec`. It is based on the stale PR from @nicolo-ribaudo (many thanks!!) https://github.com/zloirock/core-js/pull/492.
Changes include:
- Rebased original work from @nicolo-ribaudo (Added `Co-authored-by` info in commit)
- Kept original implementation of `es.string.split`
- Implemented anchored sticky flag bahvior (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/sticky#Anchored_sticky_flag)
- Implemented `RegExp#test` delegation to `RegExp#exec`
- Adapted compat data and added tests
Tested in a multitude of browser versions using BrowserStack starting from the minimum supported versions of  `core-js`.
My goal was to make …
> Sticky RegExp 'y' and RegExp#test delegation

- packages/core-js/internals/fix-regexp-well-known-symbol-logic.js
- packages/core-js/modules/es.string.replace.js
Fixes #471 in Safari. Not sure if this falls within the scope of core-js or not since the behavior of `$n` when n > m is supposed to be implementation-defined, which I think means Safari can do whatever they want?
> fixes #471

- packages/core-js/internals/task.js
> Do not use postMessage on file:// protocols

- packages/core-js/postinstall.js
When installing multiple packages that depend on core-js, the postinstall message will pop up mutiple times which will add unnecessary verbosity to the terminal log. I know #767, #548, #797, #757, #781 ,#729, #708, refer to this problem and since @zloirock refuses to remove this, lets limit it to one time so that verbosity gets truncated to the least.
> limit postinstall ad to show only one time

- packages/core-js/modules/web.url-search-params.js
Just a tiny thing I noticed in URLSearchParams
`appent` => `append`
> Fix typo in a comment

- packages/core-js/internals/global.js
There are some customized environments. New Function are not allowed .
this code is from regenerator
https://github.com/facebook/regenerator/blob/3db5564ff18e3f5bdafc4577522b41a006cc2c91/packages/regenerator-runtime/runtime-module.js#L10
> fix: some runtime can't use new Function

- packages/core-js/internals/task.js
On my ios device, when I run html with file protocol, the console will get an error,
Although [#771 ] has resolve this problem,  I think there has some other issue, because ```!fails(post)``` will run before ```location.protocol !== 'file:'``` ，and ```post``` method will be call,  then postMessage will be call. There was a problem
```
var post = function (id) {
// old engines have not location.origin
global.postMessage(id + '', location.protocol + '//' + location.host);
};
```
so I switch this position
> fix: resolve postMessage take a error on ios when protocol is file

- README.md
- packages/core-js-builder/README.md
- packages/core-js-builder/index.js
blacklist is racial offensive and can easely be changed by other terms as `exclude` or `denylist`.
I've choose `exclude` because I think it fits better than denylist in this context. But I can change it.
> refactor(core-js-builder): change blacklist term

- packages/core-js/internals/engine-is-webos-webkit.js
- packages/core-js/internals/microtask.js
> microtask, don't use MutationObserver on WebOS Webkit

- packages/core-js/internals/has.js
`ToObject` is now called before `ToPropertyKey` https://github.com/tc39/proposal-accessible-object-hasownproperty/commit/d74b1776d54e7e7ca070bba749b63cebb51d2aaf
I'm not sure if this is the right place to do this since its an internal method
> Update hasOwn to reflect change in operation order

- CHANGELOG.md
- README.md
- packages/core-js-compat/src/data.js
- packages/core-js/internals/array-sort.js
- packages/core-js/internals/engine-ff-version.js
- packages/core-js/internals/engine-is-ie-or-edge.js
- packages/core-js/internals/engine-webkit-version.js
- packages/core-js/internals/object-prototype-accessors-forced.js
- packages/core-js/modules/es.array.sort.js
- packages/core-js/modules/es.typed-array.sort.js
- tests/compat/tests.js
- tests/pure/es.array.sort.js
- tests/tests/es.array.sort.js
- tests/tests/es.typed-array.sort.js
> [WIP] Add polyfill of stable sort

- packages/core-js-compat/src/data.js
- packages/core-js-compat/targets-parser.js
To get this running on the current version of Rhino I needed to:
* Change `GLOBAL` in `tests.js` to equal `global`
* Replace `console.log` with `print`
* Return `false` for "es.string.search" because the code causes an NPE
These (in particular number 3) are good little tasks to fix upstream in Rhino though
Then it ran no problem with `java -jar rhino.jar -version 200 -require ./node-runner.js`
> Add compat data for rhino JS engine

- packages/core-js/internals/object-create.js
If you modify this part, it works well in WSH.
If `NullProtoObject()` fails, create an `htmlfile` object immediately without checking `document.domain`.
> Fix crash in `NullProtoObjectViaIFrame()` on WSH

- packages/core-js/internals/engine-is-ios-pebble.js
- packages/core-js/internals/microtask.js
The iOS Pebble app bundles its own copy of JavaScriptCore. This version includes a Promise constructor, but it's completely broken. The Promise polyfill detects this, but microtasks try to use it anyway.
> Fix microtasks on iOS Pebble

- packages/core-js/modules/es.function.name.js
- tests/tests/es.function.name.js
Supports any of:
-- `function \s* name`
-- `function \s* /* multi-line comment */ \s* name`
-- `function \s* // single-line comment [\r\n]+ \s* name`
> Comprehensive function name lookup

- CHANGELOG.md
- packages/core-js/internals/regexp-exec.js
- packages/core-js/internals/regexp-sticky-helpers.js
- packages/core-js/modules/es.regexp.constructor.js
- packages/core-js/modules/es.regexp.sticky.js
> Added a workaround for a UC Browser specific version bug with unobservable `RegExp#sticky` flag

- CHANGELOG.md
- packages/core-js/modules/es.string.at-alternative.js
- packages/core-js/modules/esnext.string.at.js
- tests/compat/tests.js
- tests/pure/es.string.at-alternative.js
- tests/pure/esnext.string.at.js
- tests/tests/es.string.at-alternative.js
- tests/tests/esnext.string.at.js
For a long time, modern `String#at` was not added because of the conflict with [an obsolete proposal](https://github.com/mathiasbynens/String.prototype.at).
However, even now loading `core-js` with stage-0 proposals can break modern `String#at`.
We can't just remove this proposal before `core-js@4` since it will break too many cases.
However, we can bring the obsolete `String#at` module semantics closer to the modern `String#at` for avoiding the most conflicts. It's mainly allowing negative indexes, but with saving multibyte semantic.
> Legacy `String#at` workaround

- CHANGELOG.md
- README.md
- packages/core-js-compat/src/data.mjs
- packages/core-js-compat/src/modules-by-versions.mjs
- packages/core-js/features/array/group-by-map.js
- packages/core-js/features/array/index.js
- packages/core-js/features/array/virtual/group-by-map.js
- packages/core-js/features/array/virtual/index.js
- packages/core-js/internals/array-group-by.js
- packages/core-js/modules/esnext.array.group-by-map.js
- packages/core-js/modules/esnext.array.group-by.js
- packages/core-js/modules/esnext.typed-array.from-async.js
- packages/core-js/modules/esnext.typed-array.group-by.js
- packages/core-js/proposals/array-from-async.js
- packages/core-js/proposals/array-grouping.js
- packages/core-js/stage/1.js
- packages/core-js/stage/2.js
- scripts/check-compat-tests.mjs
- tests/commonjs.mjs
- tests/compat/tests.js
- tests/pure/esnext.array.group-by-map.js
- tests/pure/esnext.array.group-by.js
- tests/tests/esnext.array.group-by-map.js
- tests/tests/esnext.array.group-by.js
https://github.com/babel/proposals/issues/77
---
Separately:
> Changes from October 2021 TC39 meeting

- CHANGELOG.md
- README.md
- packages/core-js-compat/src/data.mjs
- packages/core-js-compat/src/modules-by-versions.mjs
- packages/core-js/es/number/index.js
- packages/core-js/es/number/to-exponential.js
- packages/core-js/es/number/virtual/index.js
- packages/core-js/es/number/virtual/to-exponential.js
- packages/core-js/features/number/to-exponential.js
- packages/core-js/features/number/virtual/to-exponential.js
- packages/core-js/internals/math-log10.js
- packages/core-js/modules/es.math.log10.js
- packages/core-js/modules/es.number.to-exponential.js
- packages/core-js/modules/es.number.to-fixed.js
- packages/core-js/stable/number/to-exponential.js
- packages/core-js/stable/number/virtual/to-exponential.js
- tests/commonjs.mjs
- tests/compat/tests.js
- tests/pure/es.number.to-exponential.js
- tests/pure/es.number.to-fixed.js
- tests/tests/es.number.to-exponential.js
- tests/tests/es.number.to-fixed.js
Fixes [those](https://github.com/kangax/compat-table/pull/1752) and some other bugs.
> Add `Number.prototype.toExponential` polyfill

- packages/core-js/internals/microtask.js
Some functions provide macrotask API when the system does not support microtask, but one of them has the wrong name, it should be `window.postMessage` instead of `window.postMessag`, so I try to fix it.
> Fix comment of microtask for other environments

- CHANGELOG.md
- packages/core-js-compat/src/data.mjs
- packages/core-js/internals/promise-constructor-detection.js
- tests/compat/tests.js
https://github.com/denoland/deno/releases/tag/v1.24.0
https://github.com/mdn/browser-compat-data/pull/17054
> Polyfill `Promise` with `unhandledrejection` event support (browser style) in Deno < 1.24

- packages/core-js/internals/function-uncurry-this.js
Under Nashorn, certain class methods such as `String#startsWith()`, which would normally be defined as members of String.prototype,
```
> ''.startsWith === String.prototype.startsWith
< true
```
are instead defined in Java bytecode:
```
> java_import 'javax.script.ScriptEngineManager'
> engine = ScriptEngineManager.new.get_engine_by_name('nashorn')
> engine.eval("''.startsWith === String.prototype.startsWith")
< false
> engine.eval("''.endsWith")
< #<Java::JdkDynalinkBeans::SimpleDynamicMethod:0x123ca460>
```
This means that they cannot be invoked with .call, .bind, and .apply in a normal way:
```
> engine.eval("'foo'.startsWith('f')")
< true
> engine.eval("'foo'.startsWith.call('foo', 'f')")
16: from javax.script.AbstractScriptEngine.eval(javax/script/AbstractScriptEngine.java:264)
15: …
```
> Fix `uncurryThis` on Nashorn

- CHANGELOG.md
- packages/core-js-compat/README.md
- packages/core-js-compat/compat.js
- tests/compat-tools/compat.mjs
For example, what modules are NOT required for the `esmodules` target?
```js
import compat from 'core-js-compat';
const { list } = compat({ targets: { esmodules: true }, inverse: true });
/* =>
[
"es.symbol",
"es.symbol.has-instance",
"es.symbol.is-concat-spreadable",
"es.symbol.iterator",
"es.symbol.species",
"es.symbol.to-primitive",
"es.symbol.to-string-tag",
"es.symbol.unscopables",
"es.error.to-string",
"es.array.concat",
"es.array.copy-within",
"es.array.every",
"es.array.fill",
"es.array.filter",
"es.array.find",
"es.array.find-index",
"es.array.for-each",
"es.array.from",
"es.array.index-of",
"es.array.is-array",
"es.array.join",
"es.array.last-index-of",
"es.array.map",
"es.array.of",
"es.array.slice",
"es.array.some",
"es.array.species",
"es.array.splice", …
```
> Add `inverse` option to `core-js-compat`

- CHANGELOG.md
- packages/core-js/internals/array-from-async.js
- packages/core-js/internals/async-from-sync-iterator.js
- packages/core-js/internals/get-async-iterator.js
- packages/core-js/modules/esnext.async-iterator.from.js
- packages/core-js/modules/esnext.iterator.from.js
- packages/core-js/modules/esnext.iterator.to-async.js
- tests/pure/esnext.async-iterator.from.js
- tests/pure/esnext.iterator.from.js
- tests/tests/esnext.async-iterator.from.js
- tests/tests/esnext.iterator.from.js
- Early exit on broken .next in missed cases of `{ Iterator, AsyncIterator }.from`, https://github.com/tc39/proposal-iterator-helpers/pull/232
Waiting for resolutions of some other PRs / issues like https://github.com/tc39/proposal-iterator-helpers/pull/233.
> Updates of Iterator helpers proposal

- CHANGELOG.md
- README.md
- packages/core-js-compat/src/data.mjs
- packages/core-js-compat/src/modules-by-versions.mjs
- packages/core-js-pure/override/modules/web.self.js
- packages/core-js/actual/self.js
- packages/core-js/full/self.js
- packages/core-js/modules/web.self.js
- packages/core-js/stable/self.js
- packages/core-js/web/index.js
- tests/commonjs.mjs
- tests/compat/tests.js
- tests/pure/web.self.js
- tests/tests/web.self.js
The [Minimum Common Web Platform API](https://common-min-api.proposal.wintercg.org/) implies the presence of `self` in all web-interoperable runtimes.
By the [spec](https://html.spec.whatwg.org/multipage/window-object.html#dom-self), it should be a getter.
However, some old and even actual environments add it as a usual property.
https://github.com/denoland/deno/issues/15765
Initially, I was skeptical about the compatibility of this with NodeJS, however, exploring GitHub shows that detection of missed `self` is usually used only in testing environments or in complex with other methods and `self` is polyfilled too often.
https://github.com/wintercg/proposal-common-minimum-api/issues/28
Thoughts?
> Add `self`

- CHANGELOG.md
- README.md
- packages/core-js-compat/src/data.mjs
- packages/core-js-compat/src/modules-by-versions.mjs
- packages/core-js/full/function/demethodize.js
- packages/core-js/full/function/index.js
- packages/core-js/full/function/virtual/demethodize.js
- packages/core-js/full/function/virtual/index.js
- packages/core-js/full/instance/demethodize.js
- packages/core-js/internals/function-demethodize.js
- packages/core-js/modules/esnext.function.demethodize.js
- packages/core-js/proposals/function-demethodize.js
- packages/core-js/proposals/function-un-this.js
- packages/core-js/stage/0.js
- tests/compat-data/tests-coverage.mjs
- tests/compat/tests.js
- tests/entries/unit.mjs
- tests/unit-global/esnext.function.demethodize.js
- tests/unit-global/esnext.function.un-this.js
- tests/unit-pure/esnext.function.demethodize.js
It was renamed a long time ago, I wanted to wait when those changes will be present to TC39. However, since it's not present for a long time, it's better to rename it to avoid confusion.
> Rename `Function.prototype.unThis` Stage 0 proposal and method to `Function.prototype.demethodize`

- packages/core-js/internals/symbol-constructor-detection.js
The `String` constructor has a special case for `Symbol` conversions: https://tc39.es/ecma262/#sec-string-constructor-string-value
a. If NewTarget is undefined and value is a Symbol, return
SymbolDescriptiveString(value).
b. Let s be ? ToString(value).
Therefore, the only difference between `String(value)` and `value + ''` is that the latter will throw for symbols.
Terser uses this to advantage by replacing invocations of `String(...)` with `... + ''`. Terser, to its credit, has this behavior gated behind the `unsafe` flag with the following documentation: "It enables some transformations that might break code logic in certain contrived cases, but should be fine for most code." For this particular code it is *not* fine though.
Under WebPack, Terser is typically run per chunk rather than …
> Fix `Symbol` compatibility detection under Terser

- CHANGELOG.md
- README.md
- packages/core-js-compat/src/data.mjs
- packages/core-js-compat/src/modules-by-versions.mjs
- packages/core-js/actual/function/index.js
- packages/core-js/actual/function/metadata.js
- packages/core-js/actual/symbol/index.js
- packages/core-js/actual/symbol/metadata.js
- packages/core-js/full/function/metadata.js
- packages/core-js/full/symbol/index.js
- packages/core-js/full/symbol/metadata.js
- packages/core-js/modules/esnext.function.metadata.js
- packages/core-js/proposals/decorator-metadata-v2.js
- packages/core-js/stage/2.js
- packages/core-js/stage/3.js
- tests/compat/tests.js
- tests/entries/unit.mjs
- tests/unit-global/esnext.function.metadata.js
- tests/unit-pure/esnext.function.metadata.js
- tests/unit-pure/esnext.symbol.metadata.js
- [Decorator Metadata proposal](https://github.com/tc39/proposal-decorator-metadata):
- Moved to Stage 3, [May 2023 TC39 meeting](https://github.com/babel/proposals/issues/88#issuecomment-1553366034)
- Added `Function.prototype[Symbol.metadata]` (`=== null`), [May 2023 TC39 meeting](https://github.com/babel/proposals/issues/88#issuecomment-1550313363)
- Added `/actual/` entries
> Update Decorator Metadata proposal

- CHANGELOG.md
- README.md
- packages/core-js-compat/src/data.mjs
- packages/core-js-compat/src/modules-by-versions.mjs
- packages/core-js/full/object/group-by.js
- packages/core-js/full/object/index.js
- packages/core-js/modules/esnext.object.group-by.js
- packages/core-js/proposals/array-grouping-v2.js
- packages/core-js/stage/2.js
- packages/core-js/stage/3.js
- tests/compat/tests.js
- tests/entries/unit.mjs
- tests/unit-global/esnext.map.group-by.js
- tests/unit-global/esnext.object.group-by.js
- tests/unit-pure/esnext.map.group-by.js
- tests/unit-pure/esnext.object.group-by.js
- [`Array` grouping proposal](https://github.com/tc39/proposal-array-grouping):
- Because of the [web compat issue](https://github.com/tc39/proposal-array-grouping/issues/44), [moved from prototype to static methods](https://github.com/tc39/proposal-array-grouping/pull/47), [May 2023 TC39 meeting](https://github.com/babel/proposals/issues/88#issuecomment-1553350818). Added:
- `Object.groupBy`
- `Map.groupBy`
- Demoted to stage 2
Fixes #1249
> `Array` grouping proposal changes

- CHANGELOG.md
- packages/core-js-builder/index.d.ts
- packages/core-js-compat/compat.d.ts
- packages/core-js-compat/get-modules-list-for-target-version.d.ts
- packages/core-js-compat/index.d.ts
- packages/core-js-compat/package.json
- packages/core-js-compat/shared.d.ts
- tests/type-definitions/compat.ts
Reuse it for the core-js-builder declarations to prevent duplicated code
> Add typescript declarations for core-js-compat

- CHANGELOG.md
- README.md
- packages/core-js/actual/async-disposable-stack/constructor.js
- packages/core-js/actual/async-disposable-stack/index.js
- packages/core-js/actual/async-iterator/async-dispose.js
- packages/core-js/actual/async-iterator/index.js
- packages/core-js/actual/symbol/async-dispose.js
- packages/core-js/actual/symbol/index.js
- packages/core-js/full/async-disposable-stack/constructor.js
- packages/core-js/full/async-disposable-stack/index.js
- packages/core-js/full/async-iterator/async-dispose.js
- packages/core-js/full/async-iterator/index.js
- packages/core-js/full/symbol/async-dispose.js
- packages/core-js/full/symbol/index.js
- packages/core-js/modules/esnext.async-disposable-stack.constructor.js
- packages/core-js/proposals/async-explicit-resource-management.js
- packages/core-js/proposals/explicit-resource-management.js
- packages/core-js/stage/2.js
- tests/entries/unit.mjs
~~Waiting for stage 3~~, ~~https://github.com/tc39/agendas/blob/main/2023/01.md~~, ~~https://github.com/tc39/agendas/blob/main/2023/03.md~~
https://github.com/tc39/proposal-explicit-resource-management/pull/154
> Move Async explicit resource management back into the initial proposal

- packages/core-js/internals/ieee754.js
- tests/unit-global/esnext.math.f16round.js
- tests/unit-pure/esnext.math.f16round.js
The decimal part of mantissa variable is truncated by bitwise operations, but it should be rounded (to even).
related https://github.com/petamoriken/float16/issues/952
> Fix IEEE754 rounding rule from truncation to roundTiesToEven

- CHANGELOG.md
- README.md
- packages/core-js-compat/src/data.mjs
- packages/core-js-compat/src/modules-by-versions.mjs
- packages/core-js/full/regexp/escape.js
- packages/core-js/full/regexp/index.js
- packages/core-js/modules/esnext.regexp.escape.js
- packages/core-js/proposals/regexp-escaping.js
- packages/core-js/stage/2.js
- tests/compat/tests.js
- tests/entries/unit.mjs
- tests/unit-global/esnext.regexp.escape.js
- tests/unit-pure/esnext.regexp.escape.js
https://github.com/tc39/proposal-regex-escaping
Includes a fix for https://github.com/tc39/proposal-regex-escaping/issues/62
> Re-introduced `RegExp` escaping stage 2 proposal

- CHANGELOG.md
- packages/core-js/internals/global.js
Fixes #1303 by adding a check on `this` as proposed in #1303.
> Fix global object retrieval on Duktape

- packages/core-js/internals/create-property.js
This PR is for https://github.com/zloirock/core-js/issues/1322
The changes are as follows
```js
module.exports = function (object, key, value) {
var propertyKey = toPropertyKey(key);
if (propertyKey in object) definePropertyModule.f(object, propertyKey, createPropertyDescriptor(0, value));
else object[propertyKey] = value;
};
```
```js
module.exports = function (object, key, value) {
var propertyKey = toPropertyKey(key);
definePropertyModule.f(object, propertyKey, createPropertyDescriptor(0, value));
};
```
I am not certain about the impact of this patch on performance - in case the existing code was intentionally written for performance benefits like JIT optimization, please handle it appropriately at your discretion.
> Fix create-property.js

- packages/core-js/internals/array-reduce.js
This PR is about fixing [issue/1327](https://github.com/zloirock/core-js/issues/1327)
Missed check for [line 4 of spec.](https://262.ecma-international.org/14.0/#sec-array.prototype.reduce) is added
> Add missed check in `array-reduce.js`

- packages/core-js/internals/object-set-prototype-of.js
This PR is about fixing [issue/1329](https://github.com/zloirock/core-js/issues/1329)
```js
const f = require('core-js-pure/actual/object/set-prototype-of');
f(1, {}) === 1; // This should be true, without throwing
```
`Object.setPrototypeOf` should not throw when `O` is coercible - This is the related [spec](https://tc39.es/ecma262/#sec-object.setprototypeof)
> Fix Object.setPrototypeOf

- packages/core-js/internals/array-from.js
Following code behaves differently depending on whether the native version is loaded, or if the polyfill is required and loaded:
```javascript
const f = require("core-js-pure/es/array/from");
const a = function () {
throw 42;
};
const b = {};
b[Symbol.iterator] = () => undefined
f.call(a, b) // throw '42' in native, throw 'TypeError' in polyfill
```
The difference comes from the order of construction and type checking - `construct` should be done first. [spec](https://tc39.es/ecma262/#sec-array.from)
```javascript
try {
f.call(a, b)
} catch (e) {
e === 42 // This should be true
}
```
> Fix `Array.from`

- packages/core-js/modules/es.regexp.constructor.js
- tests/unit-global/es.regexp.constructor.js
`handleNCG` method from [es.regexp.constructor](https://github.com/zloirock/core-js/blob/master/packages/core-js/modules/es.regexp.constructor.js) does not work correctly in some cases.
If named captured group placed inside non-capturing group(or other group, that doesn't follow `(?<group_name>...)` pattern) then group id counter extra incremented.
```js
case chr === '(':
if (exec(IS_NCG, stringSlice(string, index + 1))) {
index += 2;
ncg = true;
// where increment is needed
}
result += chr;
groupid++;  // where actually incremented
continue;
```
Real example: [H_REGEX](https://github.com/microsoft/vscode/blob/main/src/vs/base/browser/dom.ts#L2258C1-L2258C110) from vscode repository.
`const H_REGEX = /(?<tag>[\w\-]+)?(?:#(?<id>[\w\-]+))?(?<class>(?:\.(?:[\w\-]+))*)(?:@(?<name>(?:[\w\_])+)) …
> Fix `es.regexp.constructor - handleNCG`  - consider captured groups inside non-capturing groups

- packages/core-js/modules/web.url-search-params.constructor.js
- tests/unit-global/web.url-search-params.js
- tests/unit-pure/web.url-search-params.js
> Percent decode

- packages/core-js/modules/esnext.data-view.get-float16.js
- packages/core-js/modules/esnext.data-view.set-float16.js
Hello!
Sorry I'm not really familiar with the code style of core-js -- feel free to modify this PR in any way.
This PR adds methods for packing/unpacking float16 values (instead of those from `internals/ieee754.js`) based on my code from [here](https://stackoverflow.com/a/78696004/20323848) (`roundTiesToEven` function taken from `internals/math-float-round.js`). They should be 100% IEEE754-compliant but are untested (would be great if you could help with that).
Packing is appoximately 15-20 times faster on my machine (running on an array of thousand values, ~16K ops/s vs ~900 ops/s) tested with the following JSBench code:
<details>
<summary>Setup</summary>
```js
const N = 1E3;
const floats = [];
const results = [];
for (let i = 0; i < N; i++) {
floats[i] = Math.random() * 2 ** (10 * …
```
> Make float16 handling more performant

- CHANGELOG.md
- packages/core-js-compat/src/data.mjs
- packages/core-js/modules/esnext.uint8-array.set-from-base64.js
- tests/compat/tests.js
Workaround for bug [290829](https://bugs.webkit.org/show_bug.cgi?id=290829) in a Linux build of WebKit
> Check correct behavior of Uint8Array.setFromBase64

- CHANGELOG.md
- packages/core-js/internals/async-from-sync-iterator.js
- tests/unit-global/esnext.array.from-async.js
- tests/unit-global/esnext.async-iterator.from.js
- tests/unit-global/esnext.iterator.to-async.js
- tests/unit-pure/esnext.array.from-async.js
- tests/unit-pure/esnext.async-iterator.from.js
- tests/unit-pure/esnext.iterator.to-async.js
Implementation of [tc39/ecma262#2600](https://github.com/tc39/ecma262/pull/2600)
Affected methods:
- `Array.prototype.fromAsync` (due to the lack of async feature detection capability  - temporarily, only in own core-js implementation)
- `AsyncIterator.prototype.from`
- `Iterator.prototype.toAsync`
> Close sync iterables when they yield rejected promises

- .github/workflows/ci.yml
- CHANGELOG.md
- packages/core-js-compat/src/data.mjs
- packages/core-js/internals/set-difference.js
- packages/core-js/modules/es.set.difference.v2.js
- tests/compat/tests.js
- tests/unit-global/es.set.difference.js
- tests/unit-pure/es.set.difference.js
- Added feature detection for a [bug](https://bugs.webkit.org/show_bug.cgi?id=288595)
- Fixed this bug in own implementation
- Updated support of `Set.prototype.difference` in Bun (from 1.2.5)
- Disabled support of `Set.prototype.difference` in Safari
> Fix `Set.prototype.difference` bug occurs when `this` is updated

- README.md
`core-js` supports [`DisposableStack.prototype.move`](https://github.com/zloirock/core-js/blob/faa856db4d6f2962aafc9c855ccf2a5bb71ceffd/packages/core-js/modules/esnext.disposable-stack.constructor.js#L91-L99) and [`AsyncDisposableStack.prototype.move`](https://github.com/zloirock/core-js/blob/faa856db4d6f2962aafc9c855ccf2a5bb71ceffd/packages/core-js/modules/esnext.async-disposable-stack.constructor.js#L108-L116)  but it isn't mentioned from README.md.
So this PR updates README to add `move` methods.
> Update README to add `move` methods for ERM

- CHANGELOG.md
- packages/core-js-compat/src/data.mjs
- packages/core-js/modules/es.typed-array.with.js
- tests/compat/tests.js
- tests/unit-global/es.typed-array.with.js
- Added feature detection for WebKit bug: `TypedArray.prototype.with` should truncate negative fractional index to zero, but instead throws an error
- `TypedArray.prototype.with` marked as unsupported in Safari and Bun
> Feature detection for WebKit bug in `TypedArray#with`

- CHANGELOG.md
- packages/core-js-compat/src/data.mjs
- packages/core-js/modules/es.iterator.from.js
- tests/compat/tests.js
- tests/unit-global/es.iterator.from.js
- tests/unit-pure/es.iterator.from.js
Added feature detection for [a bug](https://bugs.webkit.org/show_bug.cgi?id=288714) in WebKit: throw an error when underlying iterator's return method is null. Affected method `Iterator.from`
> `Iterator.from` bug in WebKit

- packages/core-js/modules/esnext.uint8-array.to-hex.js
- tests/unit-global/esnext.uint8-array.to-hex.js
> fix: update `Uint8Array.prototype.toHex` method to handle incorrect behavior in v8 staging

- packages/core-js/modules/esnext.uint8-array.from-base64.js
- packages/core-js/modules/esnext.uint8-array.set-from-base64.js
- packages/core-js/modules/esnext.uint8-array.to-base64.js
- tests/compat/tests.js
> fix: add checks for incorrect behavior in `Uint8Array.fromBase64`, `setFromBase64`, and `toBase64` methods

- CHANGELOG.md
- README.md
- packages/core-js-compat/src/data.mjs
- packages/core-js-compat/src/modules-by-versions.mjs
- packages/core-js/full/iterator/index.js
- packages/core-js/full/iterator/sliding.js
- packages/core-js/internals/iterator-window.js
- packages/core-js/modules/esnext.iterator.sliding.js
- packages/core-js/modules/esnext.iterator.windows.js
- packages/core-js/proposals/iterator-chunking.js
- tests/compat/tests.js
- tests/entries/unit.mjs
- tests/eslint/eslint.config.js
- tests/unit-global/esnext.iterator.sliding.js
- tests/unit-global/esnext.iterator.windows.js
- tests/unit-pure/esnext.iterator.sliding.js
- tests/unit-pure/esnext.iterator.windows.js
Added [`sliding`](https://github.com/tc39/proposal-iterator-chunking/pull/21) method to [`Iterator` chunking stage 2 proposal](https://github.com/tc39/proposal-iterator-chunking)
> Added `sliding` method to `Iterator` chunking proposal

- CHANGELOG.md
- packages/core-js-compat/src/data.mjs
- packages/core-js/modules/esnext.uint8-array.from-base64.js
- packages/core-js/modules/esnext.uint8-array.set-from-base64.js
- tests/compat/tests.js
- tests/unit-global/esnext.uint8-array.from-base64.js
- tests/unit-global/esnext.uint8-array.set-from-base64.js
Added detection of a bug when method not throws an error on incorrect length base64 string for following methods:
- `Uint8Array.fromBase64`
- `Uint8Array.prototype.setFromBase64`
> Add Webkit bug detection for Uint8Array.setFromBase64/fromBase64
