zloirock/core-js

library/modules/es6.promise.js
modules/es6.promise.js

This fixes the subclass problems with Promise on Firefox.
A different alternative is to try to patch `Promise.prototype.{then,catch}` instead of overriding the entire Promise implementation... but then we might want to expand our subclass test coverage to double-check that `Promise.all`, `Promise.race`, etc don't have any subclass issues.

Use our Promise implementation if native Promises don't subclass properly

---

modules/$.js

Fixes #86
Line 2-31 is taken from https://github.com/lodash/lodash/blob/3.10.0/lodash.js#L251-274
For more information see: https://github.com/zloirock/core-js/issues/86#issuecomment-120399476

Get correct global object in Firefox extensions

---

README.md
stage/1.js
stage/2.js
stage/3.js
stage/4.js

Object.values/Object.entries has been moved to stage 4 from 3
System.global has been moved to stage 2 from 1
https://github.com/tc39/ecma262/pull/506

Move es7 proposals to upper stage

---

modules/_html.js

_html module: document variable should be referenced from _global file.

---

README.md
library/stage/1.js
library/stage/2.js
library/stage/3.js
library/stage/4.js
stage/1.js
stage/2.js
stage/3.js
stage/4.js

- String trimming → Stage 2
- Object.getOwnPropertyDescriptors → Stage 4
- String padding → Stage 4

Update es7+ proposals

---

library/modules/es6.promise.js
modules/es6.promise.js

I've found an issue with core-js Promises when used in Node 4x. Using the following script demonstrates that when [domains](https://nodejs.org/docs/latest-v4.x/api/domain.html) are in use and a `then()` callback throws an error, the active domain is left in an entered state. This causes the domain to not be garbage collected, leading to memory leaks of not just the domain, but of anything added to the domain (a pretty big leak when using them to handle http server errors as outlined in the domain documentation).
```js
'use strict';
var core = require('core-js/library');
var domain = require('domain');
var Type = {
'core': core.Promise,
'native': Promise
};
var type = process.argv[2]; // `node thisfile.js core` or `node thisfile.js native`
console.log('using %s', type);
var P = Type[type]; …
```

[Feedback needed] fix; exit all manually entered NodeJS domains

---

packages/core-js/internals/fix-regexp-well-known-symbol-logic.js
packages/core-js/modules/es.string.replace.js

Most changes are just whitespace, you can review this PR at https://github.com/zloirock/core-js/pull/434/files?w=1

Polyfll named groups in RegExp#@@replace

---

README.md

This markdown link seems to be wrong. Just updating.

update trim-left README link

---

docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md

Some useBuilIns references should be useBuiltIns.

Fix some typo's related to useBuiltIns

---

README.md
packages/core-js/stage/0.js
packages/core-js/stage/1.js

per https://github.com/babel/proposals/issues/57#issuecomment-477335963

Move `Promise.any` to stage 1

---

README.md
packages/core-js/stage/2.js
packages/core-js/stage/3.js

per https://github.com/babel/proposals/issues/57#issuecomment-476837985

Move `Promise.allSettled` to stage 3

---

packages/core-js/scripts/postinstall.js

When you click on the link, ) is appended with.
ex) https://github.com/zloirock/core-js)

fix url on postinstall

---

CHANGELOG.md
README.md
packages/core-js/stage/2.js
packages/core-js/stage/3.js

per agenda of the next TC39 meeting

Move `String#replaceAll` to stage 3

---

CHANGELOG.md
README.md
packages/core-js/modules/esnext.aggregate-error.js
packages/core-js/stage/2.js
packages/core-js/stage/3.js

per agenda of the next TC39 meeting

Move `Promise.any` to stage 3

---

packages/core-js/postinstall.js

chore: Remove ads if OPEN_SOURCE_CONTRIBUTOR

---

packages/core-js/modules/web.url.js

Context: https://travis-ci.org/github/zloirock/core-js/jobs/666685098#L226

chore: Make unicorn/regex-shorthand happy

---

packages/core-js/postinstall.js

Revert "limit postinstall ad to show only one time"

---

docs/zh_CN/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md

translate docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md file to Chinese

feature translate

---

README.md

Resolve https://github.com/zloirock/core-js/issues/619#issuecomment-522682046

Add info about Google Maps conflicts

---

docs/zh_CN/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md

[FIX]: fix text error

---

CHANGELOG.md
README.md
packages/core-js-compat/src/data.mjs
packages/core-js-compat/src/modules-by-versions.mjs
packages/core-js/features/function/index.js
packages/core-js/features/function/is-callable.js
packages/core-js/features/function/is-constructor.js
packages/core-js/internals/is-constructor.js
packages/core-js/modules/esnext.function.is-callable.js
packages/core-js/modules/esnext.function.is-constructor.js
packages/core-js/proposals/function-is-callable-is-constructor.js
packages/core-js/stage/0.js
tests/commonjs.mjs
tests/compat/tests.js
tests/helpers/helpers.js
tests/pure/esnext.function.is-callable.js
tests/pure/esnext.function.is-constructor.js
tests/tests/esnext.function.is-callable.js
tests/tests/esnext.function.is-constructor.js

Stage 0 proposal.
https://github.com/caitp/TC39-Proposals/blob/trunk/tc39-reflect-isconstructor-iscallable.md

Add `Function.{ isCallable, isConstructor }` proposal

---

CHANGELOG.md
README.md
packages/core-js-compat/src/data.mjs
packages/core-js-compat/src/modules-by-versions.mjs
packages/core-js/features/string/cooked.js
packages/core-js/features/string/index.js
packages/core-js/modules/esnext.string.cooked.js
packages/core-js/proposals/string-cooked.js
packages/core-js/stage/0.js
packages/core-js/stage/1.js
tests/commonjs.mjs
tests/compat/tests.js
tests/pure/esnext.string.cooked.js
tests/tests/esnext.string.cooked.js

https://github.com/bathos/proposal-string-cooked
Stage 1 proposal.

Add `String.cooked` proposal

---

docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md

Enhanced the Doc by removing grammatical errors.

Corrections

---

packages/core-js-compat/src/data.mjs

As requested. Let me know if there's anything else you need on this one.

Update data for rhino 1.7.14.

---

CHANGELOG.md
README.md
packages/core-js-compat/src/data.mjs
packages/core-js-compat/src/modules-by-versions.mjs
packages/core-js/full/symbol/index.js
packages/core-js/full/symbol/metadata-key.js
packages/core-js/modules/esnext.symbol.metadata-key.js
packages/core-js/modules/esnext.symbol.metadata.js
packages/core-js/proposals/decorator-metadata.js
packages/core-js/proposals/decorators.js
packages/core-js/stage/2.js
scripts/check-compat-tests.mjs
tests/commonjs.mjs
tests/compat/tests.js
tests/pure/esnext.symbol.metadata-key.js
tests/tests/esnext.symbol.metadata-key.js

https://github.com/tc39/proposal-decorator-metadata

`Symbol.metadataKey` replaces `Symbol.metadata`

---

packages/core-js/internals/function-uncurry-this.js

Fixes https://github.com/zloirock/core-js/issues/1130

Fix more Nashorn problems

---

CHANGELOG.md
README.md
packages/core-js-compat/src/data.mjs
packages/core-js-compat/src/modules-by-versions.mjs
packages/core-js/full/instance/is-well-formed.js
packages/core-js/full/instance/to-well-formed.js
packages/core-js/full/string/index.js
packages/core-js/full/string/is-well-formed.js
packages/core-js/full/string/to-well-formed.js
packages/core-js/full/string/virtual/index.js
packages/core-js/full/string/virtual/is-well-formed.js
packages/core-js/full/string/virtual/to-well-formed.js
packages/core-js/modules/esnext.string.is-well-formed.js
packages/core-js/modules/esnext.string.to-well-formed.js
packages/core-js/proposals/well-formed-unicode-strings.js
packages/core-js/stage/2.js
tests/commonjs.mjs
tests/compat/tests.js
tests/pure/esnext.string.is-well-formed.js
tests/pure/esnext.string.to-well-formed.js
tests/tests/esnext.string.is-well-formed.js
tests/tests/esnext.string.to-well-formed.js

Stage 2.
https://github.com/tc39/proposal-is-usv-string

Add well-formed unicode strings proposal

---

CHANGELOG.md
README.md
babel.config.js
packages/core-js-compat/src/data.mjs
packages/core-js-compat/src/modules-by-versions.mjs
packages/core-js/full/string/dedent.js
packages/core-js/full/string/index.js
packages/core-js/internals/string-cooked.js
packages/core-js/internals/string-parse.js
packages/core-js/modules/esnext.string.cooked.js
packages/core-js/modules/esnext.string.dedent.js
packages/core-js/proposals/string-dedent.js
packages/core-js/stage/2.js
tests/compat/tests.js
tests/entries/content.mjs
tests/entries/unit.mjs
tests/helpers/qunit-helpers.js
tests/unit-global/esnext.string.dedent.js
tests/unit-pure/esnext.string.dedent.js

- Added [`String.dedent` stage 2 proposal](https://github.com/tc39/proposal-string-dedent)
- Method `String.dedent`
- Throws an error on non-frozen raw templates for avoiding possible breaking changes in the future, [proposal-string-dedent/75](https://github.com/tc39/proposal-string-dedent/issues/75)
cc @jridgewell

Add `String.dedent`

---

CHANGELOG.md
README.md
packages/core-js/internals/async-iterator-create-proxy.js
packages/core-js/modules/esnext.async-iterator.constructor.js
packages/core-js/modules/esnext.async-iterator.drop.js
packages/core-js/modules/esnext.async-iterator.every.js
packages/core-js/modules/esnext.async-iterator.filter.js
packages/core-js/modules/esnext.async-iterator.find.js
packages/core-js/modules/esnext.async-iterator.flat-map.js
packages/core-js/modules/esnext.async-iterator.for-each.js
packages/core-js/modules/esnext.async-iterator.from.js
packages/core-js/modules/esnext.async-iterator.map.js
packages/core-js/modules/esnext.async-iterator.reduce.js
packages/core-js/modules/esnext.async-iterator.some.js
packages/core-js/modules/esnext.async-iterator.take.js
packages/core-js/modules/esnext.async-iterator.to-array.js
packages/core-js/modules/esnext.iterator.to-async.js
packages/core-js/proposals/async-iterator-helpers.js
packages/core-js/proposals/iterator-helpers-stage-3-2.js
packages/core-js/stage/2.js
packages/core-js/stage/3.js
tests/entries/unit.mjs

Waiting for https://github.com/tc39/proposal-iterator-helpers/issues/262 / https://github.com/tc39/agendas/pull/1316

Allow interleaved mapping in `AsyncIterator` helpers

---

ORIGINAL_README.md
deno/corejs/index.js
packages/core-js-pure/override/internals/export.js
packages/core-js/internals/numeric-range-iterator.js
packages/core-js/modules/es.typed-array.set.js

This PR fixes a few typos (trial run for [a CLI I made](https://github.com/Lioness100/rspell))
:rofl:

docs: fix typos

---

packages/core-js/postinstall.js

Small grammar fix

---

CHANGELOG.md
README.md
packages/core-js-compat/src/data.mjs
packages/core-js-compat/src/modules-by-versions.mjs
packages/core-js/full/symbol/index.js
packages/core-js/full/symbol/is-registered-symbol.js
packages/core-js/full/symbol/is-well-known-symbol.js
packages/core-js/internals/symbol-is-registered.js
packages/core-js/internals/symbol-is-well-known.js
packages/core-js/modules/esnext.symbol.is-registered-symbol.js
packages/core-js/modules/esnext.symbol.is-registered.js
packages/core-js/modules/esnext.symbol.is-well-known-symbol.js
packages/core-js/modules/esnext.symbol.is-well-known.js
packages/core-js/proposals/symbol-predicates-v2.js
packages/core-js/stage/2.js
tests/compat-data/tests-coverage.mjs
tests/compat/tests.js
tests/entries/unit.mjs
tests/unit-global/esnext.symbol.is-registered-symbol.js
tests/unit-global/esnext.symbol.is-registered.js
tests/unit-global/esnext.symbol.is-well-known-symbol.js
tests/unit-global/esnext.symbol.is-well-known.js
tests/unit-pure/esnext.symbol.is-registered-symbol.js
tests/unit-pure/esnext.symbol.is-registered.js
tests/unit-pure/esnext.symbol.is-well-known-symbol.js
tests/unit-pure/esnext.symbol.is-well-known.js

https://github.com/babel/proposals/issues/88#issuecomment-1548219580

Rename the methods from the `Symbol` predicates Stage 2 proposal

---

CHANGELOG.md
README.md
packages/core-js-compat/src/data.mjs
packages/core-js-compat/src/modules-by-versions.mjs
packages/core-js/full/promise/index.js
packages/core-js/full/promise/with-resolvers.js
packages/core-js/modules/esnext.promise.with-resolvers.js
packages/core-js/proposals/promise-with-resolvers.js
packages/core-js/stage/2.js
tests/compat/tests.js
tests/entries/unit.mjs
tests/unit-global/esnext.promise.with-resolvers.js
tests/unit-pure/esnext.promise.with-resolvers.js

https://github.com/tc39/proposal-promise-with-resolvers

Add `Promise.withResolvers` Stage 2 proposal

---

packages/core-js/internals/to-length.js

This PR is about fixing [1318](https://github.com/zloirock/core-js/issues/1318#issue-2063353379).

fix `ToLength` abstract operation

---

packages/core-js/internals/array-last-index-of.js

This PR is about fixing [issue/1325](https://github.com/zloirock/core-js/issues/1325)

Fix `array-last-index-of.js`

---

CHANGELOG.md
README.md
packages/core-js/modules/esnext.promise.try.js
packages/core-js/stage/2.7.js
packages/core-js/stage/2.js
tests/unit-global/esnext.promise.try.js
tests/unit-pure/esnext.promise.try.js

Waiting for the April TC39 meeting, https://github.com/tc39/agendas/blob/main/2024/04.md

Move `Promise.try` to stage 2.7

---

CHANGELOG.md
README.md
packages/core-js/actual/math/index.js
packages/core-js/actual/math/sum-precise.js
packages/core-js/full/math/index.js
packages/core-js/full/math/sum-precise.js
packages/core-js/modules/esnext.math.sum-precise.js
packages/core-js/stage/2.7.js
packages/core-js/stage/3.js
tests/entries/unit.mjs
tests/unit-pure/esnext.math.sum-precise.js

Waiting for the [October 2024 TC39 meeting](https://github.com/tc39/agendas/blob/main/2024/10.md) results.

Move `Math.sumPrecise` to stage 3

---

README.md

The link for Array.fromAsync from mdn nor the TOC wasn't working

Fix missing ending code block

---

CHANGELOG.md
README.md
packages/core-js/stage/2.7.js
packages/core-js/stage/2.js

Waiting for the [April 2025 TC39 meeting](https://github.com/tc39/agendas/blob/main/2025/04.md#agenda-items) results.

Move `Map` upsert proposal to stage 2.7

---

CHANGELOG.md
packages/core-js-compat/src/data.mjs
packages/core-js/modules/es.iterator.reduce.js
tests/compat/tests.js
tests/unit-global/es.iterator.reduce.js
tests/unit-pure/es.iterator.reduce.js

Related to [bug](https://bugs.webkit.org/show_bug.cgi?id=291651) in WebKit

Added detection for throwing on `undefined` initial parameter in `Iterator.prototype.reduce`

---

tests/unit-global/es.set.symmetric-difference.js
tests/unit-pure/es.set.symmetric-difference.js

Added unit test for checking [bug](https://bugs.webkit.org/show_bug.cgi?id=272679) in WebKit

Set#symmetricDifference should call this.has in each iteration

---

CHANGELOG.md
README.md
packages/core-js-compat/src/data.mjs
packages/core-js-compat/src/modules-by-versions.mjs
packages/core-js/full/math/clamp.js
packages/core-js/full/math/index.js
packages/core-js/full/number/clamp.js
packages/core-js/full/number/index.js
packages/core-js/modules/esnext.math.clamp.js
packages/core-js/modules/esnext.number.clamp.js
packages/core-js/proposals/math-clamp-v2.js
packages/core-js/stage/1.js
packages/core-js/stage/2.js
tests/compat-data/tests-coverage.mjs
tests/compat/tests.js
tests/entries/unit.mjs
tests/eslint/eslint.config.js
tests/unit-global/esnext.number.clamp.js
tests/unit-pure/esnext.number.clamp.js

Reason https://github.com/tc39/proposal-math-clamp/issues/17#issuecomment-2919061520

Replace Math.clamp with Number#clamp

---

CHANGELOG.md
README.md
packages/core-js-compat/src/data.mjs
packages/core-js-compat/src/modules-by-versions.mjs
packages/core-js/full/iterator/chunks.js
packages/core-js/full/iterator/index.js
packages/core-js/full/iterator/windows.js
packages/core-js/modules/esnext.iterator.chunks.js
packages/core-js/modules/esnext.iterator.windows.js
packages/core-js/proposals/iterator-chunking.js
packages/core-js/stage/2.js
tests/compat/tests.js
tests/entries/unit.mjs
tests/eslint/eslint.config.js
tests/unit-global/esnext.iterator.chunks.js
tests/unit-global/esnext.iterator.windows.js
tests/unit-pure/esnext.iterator.chunks.js
tests/unit-pure/esnext.iterator.windows.js

Added [`Iterator` chunking stage 2 proposal](https://github.com/tc39/proposal-iterator-chunking):
- `Iterator.prototype.chunks`
- `Iterator.prototype.windows`

`Iterator` chunking proposal

---

packages/core-js/modules/esnext.iterator.windows.js

Update logic after [spec fix](https://github.com/tc39/proposal-iterator-chunking/commit/ca13b07cabbc7ddd894779ef48b87aa2933c6766)

Update logic of Iterator#windows proposal

---

CHANGELOG.md
README.md
packages/core-js/actual/iterator/concat.js
packages/core-js/actual/iterator/index.js
packages/core-js/full/iterator/concat.js
packages/core-js/full/iterator/index.js
packages/core-js/modules/esnext.iterator.concat.js
packages/core-js/stage/2.7.js
packages/core-js/stage/3.js
tests/entries/unit.mjs
tests/unit-pure/esnext.iterator.concat.js

~~Waiting for the [December 2024 TC39 meeting](https://github.com/tc39/agendas/blob/main/2024/12.md) results.~~
~~Waiting for the [May 2025 TC39 meeting](https://github.com/tc39/agendas/blob/main/2025/05.md) results.~~
Waiting for the [July 2025 TC39 meeting](https://github.com/tc39/agendas/blob/main/2025/07.md) results.

Move `Iterator` sequencing proposal to stage 3

---

CHANGELOG.md
README.md
packages/core-js/actual/map/get-or-insert-computed.js
packages/core-js/actual/map/get-or-insert.js
packages/core-js/actual/map/index.js
packages/core-js/actual/weak-map/get-or-insert-computed.js
packages/core-js/actual/weak-map/get-or-insert.js
packages/core-js/actual/weak-map/index.js
packages/core-js/full/map/get-or-insert-computed.js
packages/core-js/full/map/get-or-insert.js
packages/core-js/full/weak-map/get-or-insert-computed.js
packages/core-js/full/weak-map/get-or-insert.js
packages/core-js/modules/esnext.map.get-or-insert-computed.js
packages/core-js/modules/esnext.map.get-or-insert.js
packages/core-js/modules/esnext.weak-map.get-or-insert-computed.js
packages/core-js/modules/esnext.weak-map.get-or-insert.js
packages/core-js/stage/2.7.js
packages/core-js/stage/2.js
packages/core-js/stage/3.js
tests/entries/unit.mjs
tests/unit-pure/esnext.map.get-or-insert-computed.js
tests/unit-pure/esnext.map.get-or-insert.js
tests/unit-pure/esnext.weak-map.get-or-insert-computed.js
tests/unit-pure/esnext.weak-map.get-or-insert.js

~~Waiting for the [May 2025 TC39 meeting](https://github.com/tc39/agendas/blob/main/2025/05.md) results.~~ https://github.com/tc39/agendas/pull/1887
Waiting for the [July 2025 TC39 meeting](https://github.com/tc39/agendas/blob/main/2025/07.md) results.

Move `Map` upsert to stage 3
